### Starting to Consider What Figures to Create

```{r Importing Cleaned Datasets and Tidyverse}
library(tidyverse)
Emp_wb = read_csv('dataset/World_Bank_Employment_Data.csv', show_col_types = F)
Educ_wb = read_csv('dataset/World_Bank_Educ_Data.csv', show_col_types = F)

```

```{r Creating Potential Plots}
Emp_wb$Year <- as.Date(as.character(Emp_wb$Year), format = "%Y") 

```

```{r trying to make a map based on census data}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidycensus))
suppressPackageStartupMessages(library(sf))

v2020 <- load_variables(2020, "acs5", cache = TRUE)

concepts <- v2020 |>
  filter(str_detect(concept, '^MEDIAN INCOME'))

### Would like to analyze B19326_004 and B19326_005 (They were a dud, most likely skewed due to part-time workers)

### poverty data from ACS
poverty_test <- get_acs(
  geography = 'state',
  variables = 'B17001A_001',
  year = 2020,
  geometry = TRUE
)

### Looking at C24040_002 and C24040_029 now which are
##SEX BY INDUSTRY FOR THE FULL-TIME, YEAR-ROUND CIVILIAN EMPLOYED POPULATION 16 YEARS AND OVER for male and female


vars_df <- v2020 |>
  filter(name == 'C24040_002' | name == 'C24040_029') |>
  mutate(
    variable = name,
    gender = if_else(
      str_detect(label, 'Male'),
      'Male',
      'Female'
    ),
    .keep = 'none'
  )

gendered_employment <- get_acs(
  geography = 'state',
  variables = vars_df |> pull(variable),
  year = 2020,
  geometry = TRUE
) %>% 
  left_join(vars_df) %>%
  select(-moe, -variable, -GEOID) 
### name is state data

gendered_employment_split <- gendered_employment |>
  pivot_wider(names_from = 'gender', values_from = 'estimate')
  

total_employment <- gendered_employment |>
  group_by(geometry) |>
  summarise(total = sum(estimate))

gendered_employment_final <- st_join(gendered_employment, total_employment, join = st_equals)

```

```{r heatmap idea for median working population}
gendered_employment_split |>
  ggplot(aes(fill =  `Male`/`Female`)) + 
  geom_sf() +
  coord_sf(crs = 5070) +
  scale_fill_viridis_c(option = 'plasma')+
  theme_minimal()

### this creates two maps, which are representative of the proportion of full time, year round civilians in each state faceted by gender. I'm not sure if this is the best approach to data presentation, and I am open to other ideas
```

```{r dept of labor stuff}
income_data = read_csv("dataset/Income_dofl.csv")
### median income data split by race

income_data_clean <- income_data|>
  filter(Year != 2013 | `In / Out of New Methodology Implemented` == 'In')|>
  filter(Year != 2017 | `In / Out of New Methodology Implemented` == 'In')|>
  select(-c(1,2)) |>
  group_by(`Measure Names`) |>
  pivot_wider(names_from = `Measure Names`, values_from = `Measure Values`) |> arrange(desc(Year))
```

```{r ACS Poverty Status Data}
library(tidycensus)


desired_vars = c('B17001A_032','B17001A_003','B17001A_017', 'B17001A_046','B17001B_003','B17001B_017','B17001B_032','B17001B_046','B17001C_003','B17001C_017','B17001C_032','B17001C_046','B17001D_003','B17001D_017','B17001D_032','B17001D_046','B17001E_003','B17001E_017','B17001E_032','B17001E_046','B17001F_003','B17001F_017','B17001F_032','B17001F_046','B17001G_003','B17001G_017','B17001G_032','B17001G_046','B17001H_003','B17001H_017','B17001H_032','B17001H_046','B17001I_003','B17001I_017','B17001I_032','B17001I_046')

v2020 <- load_variables(2020, "acs5", cache = TRUE)

poverty_data <- v2020 |>
  filter(name %in% desired_vars) |>
  mutate(
    variable = name,
    gender = if_else(
      str_detect(label, 'Male'),
      'Male',
      'Female'
      ),
   race = str_extract(concept, "\\((.*?)\\)"),
   status = if_else(str_detect(label, 'above'),
                    'Above Poverty Line',
                    'Below Poverty Line'
                    ),

    .keep= 'none'
  )

poverty_data$race <- gsub("[\\(\\)]", "", trimws(poverty_data$race))
poverty_data$race <- str_to_title(poverty_data$race)

poverty_final <- get_acs(
  geography = 'state',
  variables = poverty_data |> pull(variable),
  year = 2020,
  geometry = TRUE
) |> 
  left_join(poverty_data) |>
  select(-moe, -variable, -GEOID) |>
  group_by(race, gender, NAME) |>
  mutate(
    gendered_total = sum(estimate[status == 'Above Poverty Line'], estimate[status == 'Below Poverty Line']),
    proportion = (estimate[status == 'Above Poverty Line']/gendered_total)
  ) |>
  filter(status != 'Below Poverty Line') |>
  ungroup() 

### creating difference table
poverty_diff <- poverty_final |>
  select(-estimate, -status, -gendered_total)

poverty_diff <- as_tibble(poverty_diff)

poverty_diff <- poverty_diff %>% select(-geometry)

poverty_diff_table <- poverty_diff |>
  group_by(race, NAME) |>
  mutate(`Percent Difference` = ((proportion[gender == 'Male'] - proportion[gender == 'Female'])*100)) |>
  filter(gender == 'Male') |>
  ungroup() |>
  select(-gender, -proportion) |>
  pivot_wider(names_from = race, values_from = `Percent Difference`)
### This table shows the percent difference between the proportions of males who live above the poverty line and females, split by race and state. It is a way of showing the raw data of the differences we can observe on the heat maps between races.

### creating plotted data  
poverty_plot <- poverty_final |>
  select(-estimate, -NAME, -status, -gendered_total) |>
  pivot_wider(names_from = c(gender,race), values_from = proportion, names_sep = ' ')
  
column_names <- names(poverty_plot)[-which(names(poverty_plot) == "geometry")]

for (x in column_names) {
  p <- ggplot(data = poverty_plot, aes(fill = .data[[x]])) +
    geom_sf() +
    coord_sf(crs = 5070) +
    scale_fill_viridis_c(option = 'plasma', limits = c(0.3, 1)) +
    theme_minimal() +
    theme(legend.title = element_blank()) +
    labs(title = x, caption = "Source: ACS Poverty Status Data, Extracted with tidycensus.")
  
  ggsave(paste0(x, ".jpg"), plot = p, device = "jpg")
}
```
