---
title: "Male Data Cleaning"
editor: visual
---

```{r "Reading Data and Initializing Packages"}
suppressMessages(library(readxl))
suppressMessages(library(tidyverse))

# Uncomment the following two commands if you have not run this file previously after Dylan made the changes

# acs_data_test <- read_excel("dataset/acsfinale.xlsx")
# write_csv(acs_data, file = here::here('dataset', 'ACS_data_rendered.csv'))

acs_data_test <- read_excel("dataset/acsfinale.xlsx")

write_csv(acs_data_test, file = here::here('dataset', 'ACS_data_rendered.csv'))

acs_data <- read.csv('dataset/ACS_data_rendered.csv')

state_names <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "Puerto Rico")

race_names <- c("White Alone", "White alone, not Hispanic or Latino", "Black Alone", "American Indian or Alaska Native Alone", "Asian Alone", "Native Hawaiian and Other Pacific Islander Alone", "Some other race Alone", "Two or more races", "Hispanic or Latino Origin")
```

<<<<<<< HEAD
```{r}
# Alabama
us_whitealone_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_alabama <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`Alabama...9`,
  Race = "White Alone")

# Alaska
bdh_whitealone_alaska <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...21`,
  Race = "White Alone"
)


# Arizona
bdh_whitealone_arizona <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...33`,
  Race = "White Alone"
)

# Arkansas
bdh_whitealone_arkansas <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...45`,
  Race = "White Alone"
)

# California
bdh_whitealone_california <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...57`,
  Race = "White Alone"
)

# Colorado
bdh_whitealone_colorado <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...69`,
  Race = "White Alone"
)

# Connecticut
bdh_whitealone_connecticut <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...81`,
  Race = "White Alone"
)

# Delaware
bdh_whitealone_delaware <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...93`,
  Race = "White Alone"
)

# Florida
bdh_whitealone_florida <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...105`,
  Race = "White Alone"
)

# Georgia
bdh_whitealone_georgia <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...117`,
  Race = "White Alone"
)

# Hawaii
bdh_whitealone_hawaii <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...129`,
  Race = "White Alone"
)

# Idaho
bdh_whitealone_idaho <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...141`,
  Race = "White Alone"
)

# Illinois
bdh_whitealone_illinois <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...153`,
  Race = "White Alone"
)

# Indiana
bdh_whitealone_indiana <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...165`,
  Race = "White Alone"
)

# Iowa
bdh_whitealone_iowa <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...177`,
  Race = "White Alone"
)

# Kansas
bdh_whitealone_kansas <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...189`,
  Race = "White Alone"
)

# Kentucky
bdh_whitealone_kentucky <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...201`,
  Race = "White Alone"
)

# Louisiana
bdh_whitealone_louisiana <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...213`,
  Race = "White Alone"
)

# Maine
bdh_whitealone_maine <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...225`,
  Race = "White Alone"
)

# Maryland
bdh_whitealone_maryland <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...237`,
  Race = "White Alone"
)

# Massachusetts
bdh_whitealone_massachusetts <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...249`,
  Race = "White Alone"
)

# Michigan
bdh_whitealone_michigan <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...261`,
  Race = "White Alone"
)

# Minnesota
bdh_whitealone_minnesota <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...273`,
  Race = "White Alone"
)

# Mississippi
bdh_whitealone_mississippi <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...285`,
  Race = "White Alone"
)

# Missouri
bdh_whitealone_missouri <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...397`,
  Race = "White Alone"
)

# Montana
bdh_whitealone_montana <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...309`,
  Race = "White Alone"
)

# Nebraska
bdh_whitealone_nebraska <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...321`,
  Race = "White Alone"
)

# Nevada
bdh_whitealone_nevada <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...333`,
  Race = "White Alone"
)

# New Hampshire
bdh_whitealone_newhampshire <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...345`,
  Race = "White Alone"
)

# New Jersey
bdh_whitealone_newjersey <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...357`,
  Race = "White Alone"
)

# New Mexico
bdh_whitealone_newmexico <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...369`,
  Race = "White Alone"
)

# New York
bdh_whitealone_newyork <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...381`,
  Race = "White Alone"
)

# North Carolina
bdh_whitealone_northcarolina <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...393`,
  Race = "White Alone"
)

# North Dakota
bdh_whitealone_northdakota <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...405`,
  Race = "White Alone"
)

# Ohio
bdh_whitealone_ohio <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...417`,
  Race = "White Alone"
)

# Oklahoma
bdh_whitealone_oklahoma <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...429`,
  Race = "White Alone"
)

# Oregon
bdh_whitealone_oregon <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...441`,
  Race = "White Alone"
)

# Pennsylvania
bdh_whitealone_pennsylvania <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...453`,
  Race = "White Alone"
)

# Rhode Island
bdh_whitealone_rhodeisland <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...465`,
  Race = "White Alone"
)

# South Carolina
bdh_whitealone_southcarolina <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...477`,
  Race = "White Alone"
)

# South Dakota
bdh_whitealone_southdakota <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...489`,
  Race = "White Alone"
)

# Tennessee
bdh_whitealone_tennessee <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...501`,
  Race = "White Alone"
)

# Texas
bdh_whitealone_texas <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...513`,
  Race = "White Alone"
)

# Utah
bdh_whitealone_utah <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...525`,
  Race = "White Alone"
)

# Vermont
bdh_whitealone_vermont <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...537`,
  Race = "White Alone"
)

# Virginia
bdh_whitealone_virginia <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...549`,
  Race = "White Alone"
)

# Washington
bdh_whitealone_washington <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...561`,
  Race = "White Alone"
)

# West Virginia
bdh_whitealone_westvirginia <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...573`,
  Race = "White Alone"
)

# Wisconsin
bdh_whitealone_wisconsin <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...585`,
 Race = "White Alone"
)

# Wyoming
bdh_whitealone_wyoming <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...597`,
  Race = "White Alone"
)

# Puerto Rico
bdh_whitealone_puertorico <- tibble(
  Years = us_whitealone_data$Years,
  Percentage_men = us_whitealone_data$`...597`,
  Race = "White Alone"
)

# Combine all tibbles into one
combined_data_malewhitealone <- bind_rows(
  bdh_whitealone_alabama,
  bdh_whitealone_alaska,
  bdh_whitealone_arizona,
  bdh_whitealone_arkansas,
  bdh_whitealone_california,
  bdh_whitealone_colorado,
  bdh_whitealone_connecticut,
  bdh_whitealone_delaware,
  bdh_whitealone_florida,
  bdh_whitealone_georgia,
  bdh_whitealone_hawaii,
  bdh_whitealone_idaho,
  bdh_whitealone_illinois,
  bdh_whitealone_indiana,
  bdh_whitealone_iowa,
  bdh_whitealone_kansas,
  bdh_whitealone_kentucky,
  bdh_whitealone_louisiana,
  bdh_whitealone_maine,
  bdh_whitealone_maryland,
  bdh_whitealone_massachusetts,
  bdh_whitealone_michigan,
  bdh_whitealone_minnesota,
  bdh_whitealone_mississippi,
  bdh_whitealone_missouri,
  bdh_whitealone_montana,
  bdh_whitealone_nebraska,
  bdh_whitealone_nevada,
  bdh_whitealone_newhampshire,
  bdh_whitealone_newjersey,
  bdh_whitealone_newmexico,
  bdh_whitealone_newyork,
  bdh_whitealone_northcarolina,
  bdh_whitealone_northdakota,
  bdh_whitealone_ohio,
  bdh_whitealone_oklahoma,
  bdh_whitealone_oregon,
  bdh_whitealone_pennsylvania,
  bdh_whitealone_rhodeisland,
  bdh_whitealone_southcarolina,
  bdh_whitealone_southdakota,
  bdh_whitealone_tennessee,
  bdh_whitealone_texas,
  bdh_whitealone_utah,
  bdh_whitealone_vermont,
  bdh_whitealone_virginia,
  bdh_whitealone_washington,
  bdh_whitealone_westvirginia,
  bdh_whitealone_wisconsin,
  bdh_whitealone_wyoming,
  bdh_whitealone_puertorico
)

print(combined_data_malewhitealone)
```

2.  **Male, White-alone, not Hispanic or Latino, Across all U.S. States + Puerto Rico (Status: Cleaned)**

```{r}

# Alabama
us_whitealone_data <- filter(acs_data, Label == "Bachelor's degree or higher**")
us_WhitealonenotHispanicorLatino_data <- filter(acs_data, Label == "Bachelor's degree or higher**")
bdh_wnhp_alabama <- tibble(
  Years =  us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...9`,
  Race = "White alone, not Hispanic or Latino"
)

# Alaska
bdh_wnhp_alaska <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...21`,
  Race = "White alone, not Hispanic or Latino"
)

# Arizona
bdh_wnhp_arizona <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...33`,
  Race = "White alone, not Hispanic or Latino"
)

# Arkansas
bdh_wnhp_arkansas <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...45`,
  Race = "White alone, not Hispanic or Latino"
)

# California
bdh_wnhp_california <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...53`,
  Race = "White alone, not Hispanic or Latino"
)

# Colorado
bdh_wnhp_colorado <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...65`,
  Race = "White alone, not Hispanic or Latino"
)

# Connecticut
bdh_wnhp_connecticut <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...77`,
  Race = "White alone, not Hispanic or Latino"
)

# Delaware
bdh_wnhp_delaware <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...89`,
  Race = "White alone, not Hispanic or Latino"
)

# Florida
bdh_wnhp_florida <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...101`,
  Race = "White alone, not Hispanic or Latino"
)

# Georgia
bdh_wnhp_georgia <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...113`,
  Race = "White alone, not Hispanic or Latino"
)

# Hawaii
bdh_wnhp_hawaii <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...125`,
  Race = "White alone, not Hispanic or Latino"
)

# Idaho
bdh_wnhp_idaho <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...137`,
  Race = "White alone, not Hispanic or Latino"
)

# Illinois
bdh_wnhp_illinois <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...149`,
  Race = "White alone, not Hispanic or Latino"
)

# Indiana
bdh_wnhp_indiana <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...161`,
  Race = "White alone, not Hispanic or Latino"
)

# Iowa
bdh_wnhp_iowa <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...173`,
  Race = "White alone, not Hispanic or Latino"
)

# Kansas
bdh_wnhp_kansas <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...185`,
  Race = "White alone, not Hispanic or Latino"
)

# Kentucky
bdh_wnhp_kentucky <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...197`,
  Race = "White alone, not Hispanic or Latino"
)

# Louisiana
bdh_wnhp_louisiana <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...209`,
  Race = "White alone, not Hispanic or Latino"
)

# Maine
bdh_wnhp_maine <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...221`,
  Race = "White alone, not Hispanic or Latino"
)

# Maryland
bdh_wnhp_maryland <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...233`,
  Race = "White alone, not Hispanic or Latino"
)

# Massachusetts
bdh_wnhp_massachusetts <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...245`,
  Race = "White alone, not Hispanic or Latino"
)

# Michigan
bdh_wnhp_michigan <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...257`,
  Race = "White alone, not Hispanic or Latino"
)

# Minnesota
bdh_wnhp_minnesota <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...269`,
  Race = "White alone, not Hispanic or Latino"
)

# Mississippi
bdh_wnhp_mississippi <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...281`,
  Race = "White alone, not Hispanic or Latino"
)

# Missouri
bdh_wnhp_missouri <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...293`,
  Race = "White alone, not Hispanic or Latino"
)

# Montana
bdh_wnhp_montana <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...305`,
  Race = "White alone, not Hispanic or Latino"
)

# Nebraska
bdh_wnhp_nebraska <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...317`,
  Race = "White alone, not Hispanic or Latino"
)

# Nevada
bdh_wnhp_nevada <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...329`,
  Race = "White alone, not Hispanic or Latino"
)

# New Hampshire
bdh_wnhp_newhampshire <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...341`,
  Race = "White alone, not Hispanic or Latino"
)

# New Jersey
bdh_wnhp_newjersey <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...353`,
  Race = "White alone, not Hispanic or Latino"
)

# New Mexico
bdh_wnhp_newmexico <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...365`,
  Race = "White alone, not Hispanic or Latino"
)

# New York
bdh_wnhp_newyork <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...377`,
  Race = "White alone, not Hispanic or Latino"
)

# North Carolina
bdh_wnhp_northcarolina <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...389`,
  Race = "White alone, not Hispanic or Latino"
)

# North Dakota
bdh_wnhp_northdakota <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...401`,
  Race = "White alone, not Hispanic or Latino"
)

# Ohio
bdh_wnhp_ohio <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...413`,
  Race = "White alone, not Hispanic or Latino"
)

# Oklahoma
bdh_wnhp_oklahoma <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...425`,
  Race = "White alone, not Hispanic or Latino"
)

# Oregon
bdh_wnhp_oregon <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...437`,
  Race = "White alone, not Hispanic or Latino"
)

# Pennsylvania
bdh_wnhp_pennsylvania <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...449`,
  Race = "White alone, not Hispanic or Latino"
)

# Rhode Island
bdh_wnhp_rhodeisland <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...461`,
  Race = "White alone, not Hispanic or Latino"
)

# South Carolina
bdh_wnhp_southcarolina <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...473`,
  Race = "White alone, not Hispanic or Latino"
)

# South Dakota
bdh_wnhp_southdakota <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...485`,
  Race = "White alone, not Hispanic or Latino"
)

# Tennessee
bdh_wnhp_tennessee <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...497`,
  Race = "White alone, not Hispanic or Latino"
)

# Texas
bdh_wnhp_texas <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...509`,
  Race = "White alone, not Hispanic or Latino"
)

# Utah
bdh_wnhp_utah <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...521`,
  Race = "White alone, not Hispanic or Latino"
)

# Vermont
bdh_wnhp_vermont <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...533`,
  Race = "White alone, not Hispanic or Latino"
)

# Virginia
bdh_wnhp_virginia <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...545`,
  Race = "White alone, not Hispanic or Latino"
)

# Washington
bdh_wnhp_washington <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...557`,
  Race = "White alone, not Hispanic or Latino"
)

# West Virginia
bdh_wnhp_westvirginia <- tibble(
  Years =us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...569`,
  Race = "White alone, not Hispanic or Latino"
)

# Wisconsin
bdh_wnhp_wisconsin <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...581`,
  Race = "White alone, not Hispanic or Latino"
)

# Wyoming
bdh_wnhp_wyoming <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...593`,
  Race = "White alone, not Hispanic or Latino"
)

# Puerto Rico
bdh_wnhp_puertorico <- tibble(
  Years = us_WhitealonenotHispanicorLatino_data$Years,
  Percentage_wnhp_men = us_WhitealonenotHispanicorLatino_data$`...605`,
  Race = "White alone, not Hispanic or Latino"
)

# Combine all states
combined_data_wnhp <- bind_rows(
  bdh_wnhp_alabama,
  bdh_wnhp_alaska,
  bdh_wnhp_arizona,
  bdh_wnhp_arkansas,
  bdh_wnhp_california,
  bdh_wnhp_colorado,
  bdh_wnhp_connecticut,
  bdh_wnhp_delaware,
  bdh_wnhp_florida,
  bdh_wnhp_georgia,
  bdh_wnhp_hawaii,
  bdh_wnhp_idaho,
  bdh_wnhp_illinois,
  bdh_wnhp_indiana,
  bdh_wnhp_iowa,
  bdh_wnhp_kansas,
  bdh_wnhp_kentucky,
  bdh_wnhp_louisiana,
  bdh_wnhp_maine,
  bdh_wnhp_maryland,
  bdh_wnhp_massachusetts,
  bdh_wnhp_michigan,
  bdh_wnhp_minnesota,
  bdh_wnhp_mississippi,
  bdh_wnhp_missouri,
  bdh_wnhp_montana,
  bdh_wnhp_nebraska,
  bdh_wnhp_nevada,
  bdh_wnhp_newhampshire,
  bdh_wnhp_newjersey,
  bdh_wnhp_newmexico,
  bdh_wnhp_newyork,
  bdh_wnhp_northcarolina,
  bdh_wnhp_northdakota,
  bdh_wnhp_ohio,
  bdh_wnhp_oklahoma,
  bdh_wnhp_oregon,
  bdh_wnhp_pennsylvania,
  bdh_wnhp_rhodeisland,
  bdh_wnhp_southcarolina,
  bdh_wnhp_southdakota,
  bdh_wnhp_tennessee,
  bdh_wnhp_texas,
  bdh_wnhp_utah,
  bdh_wnhp_vermont,
  bdh_wnhp_virginia,
  bdh_wnhp_washington,
  bdh_wnhp_westvirginia,
  bdh_wnhp_wisconsin,
  bdh_wnhp_wyoming,
  bdh_wnhp_puertorico
)

print(combined_data_wnhp)

```

3.  **Male, Black Alone, Across all U.S. States + Puerto Rico (Status: Cleaned)**

```{r}

# Alabama
us_blackalone_data <- filter(acs_data, Label == "Bachelor's degree or higher***")
bdh_wnhp_alabama <- tibble(
  Years =  us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...9`,
  Race = "Black Alone"
)

# Alaska
bdh_wnhp_alaska <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...21`,
  Race = "Black Alone"
)

# Arizona
bdh_wnhp_arizona <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...33`,
  Race = "Black Alone"
)

# Arkansas
bdh_wnhp_arkansas <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...45`,
  Race = "Black Alone"
)

# California
bdh_wnhp_california <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...53`,
  Race = "Black Alone"
)

# Colorado
bdh_wnhp_colorado <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...65`,
  Race = "Black Alone"
)

# Connecticut
bdh_wnhp_connecticut <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...77`,
  Race = "Black Alone"
)

# Delaware
bdh_wnhp_delaware <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...89`,
  Race = "Black Alone"
)

# Florida
bdh_wnhp_florida <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...101`,
  Race = "Black Alone"
)

# Georgia
bdh_wnhp_georgia <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...113`,
  Race = "Black Alone"
)

# Hawaii
bdh_wnhp_hawaii <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...125`,
  Race = "Black Alone"
)

# Idaho
bdh_wnhp_idaho <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...137`,
  Race = "Black Alone"
)

# Illinois
bdh_wnhp_illinois <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...149`,
  Race = "Black Alone"
)

# Indiana
bdh_wnhp_indiana <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...161`,
  Race = "Black Alone"
)

# Iowa
bdh_wnhp_iowa <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...173`,
  Race = "Black Alone"
)

# Kansas
bdh_wnhp_kansas <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...185`,
  Race = "Black Alone"
)

# Kentucky
bdh_wnhp_kentucky <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...197`,
  Race = "Black Alone"
)

# Louisiana
bdh_wnhp_louisiana <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...209`,
  Race = "Black Alone"
)

# Maine
bdh_wnhp_maine <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...221`,
  Race = "Black Alone"
)

# Maryland
bdh_wnhp_maryland <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...233`,
  Race = "Black Alone"
)

# Massachusetts
bdh_wnhp_massachusetts <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...245`,
  Race = "Black Alone"
)

# Michigan
bdh_wnhp_michigan <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...257`,
  Race = "Black Alone"
)

# Minnesota
bdh_wnhp_minnesota <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...269`,
  Race = "Black Alone"
)

# Mississippi
bdh_wnhp_mississippi <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...281`,
  Race = "Black Alone"
)

# Missouri
bdh_wnhp_missouri <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...293`,
  Race = "Black Alone"
)

# Montana
bdh_wnhp_montana <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...305`,
  Race = "Black Alone"
)

# Nebraska
bdh_wnhp_nebraska <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...317`,
  Race = "Black Alone"
)

# Nevada
bdh_wnhp_nevada <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...329`,
  Race = "Black Alone"
)

# New Hampshire
bdh_wnhp_newhampshire <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...341`,
  Race = "Black Alone"
)

# New Jersey
bdh_wnhp_newjersey <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...353`,
  Race = "Black Alone"
)

# New Mexico
bdh_wnhp_newmexico <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...365`,
  Race = "Black Alone"
)

# New York
bdh_wnhp_newyork <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...377`,
  Race = "Black Alone"
)

# North Carolina
bdh_wnhp_northcarolina <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...389`,
  Race = "Black Alone"
)

# North Dakota
bdh_wnhp_northdakota <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...401`,
  Race = "Black Alone"
)

# Ohio
bdh_wnhp_ohio <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...413`,
  Race = "Black Alone"
)

# Oklahoma
bdh_wnhp_oklahoma <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...425`,
  Race = "Black Alone"
)

# Oregon
bdh_wnhp_oregon <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...437`,
  Race = "Black Alone"
)

# Pennsylvania
bdh_wnhp_pennsylvania <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...449`,
  Race = "Black Alone"
)

# Rhode Island
bdh_wnhp_rhodeisland <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...461`,
  Race = "Black Alone"
)

# South Carolina
bdh_wnhp_southcarolina <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...473`,
  Race = "Black Alone"
)

# South Dakota
bdh_wnhp_southdakota <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...485`,
  Race = "Black Alone"
)

# Tennessee
bdh_wnhp_tennessee <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...497`,
  Race = "Black Alone"
)

# Texas
bdh_wnhp_texas <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...509`,
  Race = "Black Alone"
)

# Utah
bdh_wnhp_utah <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...521`,
  Race = "Black Alone"
)

# Vermont
bdh_wnhp_vermont <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...533`,
  Race = "Black Alone"
)

# Virginia
bdh_wnhp_virginia <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...545`,
  Race = "Black Alone"
)

# Washington
bdh_wnhp_washington <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...557`,
  Race = "Black Alone"
)

# West Virginia
bdh_wnhp_westvirginia <- tibble(
  Years =us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...569`,
  Race = "Black Alone"
)

# Wisconsin
bdh_wnhp_wisconsin <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...581`,
  Race = "Black Alone"
)

# Wyoming
bdh_wnhp_wyoming <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...593`,
  Race = "Black Alone"
)

# Puerto Rico
bdh_wnhp_puertorico <- tibble(
  Years = us_blackalone_data$Years,
  Percentage_wnhp_men = us_blackalone_data$`...605`,
  Race = "Black Alone"
)

# Combine all states
combined_data_wnhp <- bind_rows(
  bdh_wnhp_alabama,
  bdh_wnhp_alaska,
  bdh_wnhp_arizona,
  bdh_wnhp_arkansas,
  bdh_wnhp_california,
  bdh_wnhp_colorado,
  bdh_wnhp_connecticut,
  bdh_wnhp_delaware,
  bdh_wnhp_florida,
  bdh_wnhp_georgia,
  bdh_wnhp_hawaii,
  bdh_wnhp_idaho,
  bdh_wnhp_illinois,
  bdh_wnhp_indiana,
  bdh_wnhp_iowa,
  bdh_wnhp_kansas,
  bdh_wnhp_kentucky,
  bdh_wnhp_louisiana,
  bdh_wnhp_maine,
  bdh_wnhp_maryland,
  bdh_wnhp_massachusetts,
  bdh_wnhp_michigan,
  bdh_wnhp_minnesota,
  bdh_wnhp_mississippi,
  bdh_wnhp_missouri,
  bdh_wnhp_montana,
  bdh_wnhp_nebraska,
  bdh_wnhp_nevada,
  bdh_wnhp_newhampshire,
  bdh_wnhp_newjersey,
  bdh_wnhp_newmexico,
  bdh_wnhp_newyork,
  bdh_wnhp_northcarolina,
  bdh_wnhp_northdakota,
  bdh_wnhp_ohio,
  bdh_wnhp_oklahoma,
  bdh_wnhp_oregon,
  bdh_wnhp_pennsylvania,
  bdh_wnhp_rhodeisland,
  bdh_wnhp_southcarolina,
  bdh_wnhp_southdakota,
  bdh_wnhp_tennessee,
  bdh_wnhp_texas,
  bdh_wnhp_utah,
  bdh_wnhp_vermont,
  bdh_wnhp_virginia,
  bdh_wnhp_washington,
  bdh_wnhp_westvirginia,
  bdh_wnhp_wisconsin,
  bdh_wnhp_wyoming,
  bdh_wnhp_puertorico
)

print(combined_data_wnhp)

```

4.  **Male, American Indian or Alaska Native Alone, Across all U.S. States + Puerto Rico (Status: Cleaned)**

```{r}

# Alabama
us_AmericanIndianorAlaskaNativeAlone_data <- filter(acs_data, Label == "Bachelor's degree or higher****")
bdh_wnhp_alabama <- tibble(
  Years =  us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...9`,
  Race = "American Indian or Alaska Native Alone"
)

# Alaska
bdh_wnhp_alaska <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...21`,
  Race = "American Indian or Alaska Native Alone"
)

# Arizona
bdh_wnhp_arizona <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...33`,
  Race = "American Indian or Alaska Native Alone"
)

# Arkansas
bdh_wnhp_arkansas <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...45`,
  Race = "American Indian or Alaska Native Alone"
)

# California
bdh_wnhp_california <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...53`,
  Race = "American Indian or Alaska Native Alone"
)

# Colorado
bdh_wnhp_colorado <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...65`,
  Race = "American Indian or Alaska Native Alone"
)

# Connecticut
bdh_wnhp_connecticut <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...77`,
  Race = "American Indian or Alaska Native Alone"
)

# Delaware
bdh_wnhp_delaware <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...89`,
  Race = "American Indian or Alaska Native Alone"
)

# Florida
bdh_wnhp_florida <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...101`,
  Race = "American Indian or Alaska Native Alone"
)

# Georgia
bdh_wnhp_georgia <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...113`,
  Race = "American Indian or Alaska Native Alone"
)

# Hawaii
bdh_wnhp_hawaii <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...125`,
  Race = "American Indian or Alaska Native Alone"
)

# Idaho
bdh_wnhp_idaho <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...137`,
  Race = "American Indian or Alaska Native Alone"
)

# Illinois
bdh_wnhp_illinois <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...149`,
  Race = "American Indian or Alaska Native Alone"
)

# Indiana
bdh_wnhp_indiana <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...161`,
  Race = "American Indian or Alaska Native Alone"
)

# Iowa
bdh_wnhp_iowa <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...173`,
  Race = "American Indian or Alaska Native Alone"
)

# Kansas
bdh_wnhp_kansas <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...185`,
  Race = "American Indian or Alaska Native Alone"
)

# Kentucky
bdh_wnhp_kentucky <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...197`,
  Race = "American Indian or Alaska Native Alone"
)

# Louisiana
bdh_wnhp_louisiana <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...209`,
  Race = "American Indian or Alaska Native Alone"
)

# Maine
bdh_wnhp_maine <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...221`,
  Race = "American Indian or Alaska Native Alone"
)

# Maryland
bdh_wnhp_maryland <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...233`,
  Race = "American Indian or Alaska Native Alone"
)

# Massachusetts
bdh_wnhp_massachusetts <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...245`,
  Race = "American Indian or Alaska Native Alone"
)

# Michigan
bdh_wnhp_michigan <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...257`,
  Race = "American Indian or Alaska Native Alone"
)

# Minnesota
bdh_wnhp_minnesota <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...269`,
  Race = "American Indian or Alaska Native Alone"
)

# Mississippi
bdh_wnhp_mississippi <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...281`,
  Race = "American Indian or Alaska Native Alone"
)

# Missouri
bdh_wnhp_missouri <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...293`,
  Race = "American Indian or Alaska Native Alone"
)

# Montana
bdh_wnhp_montana <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...305`,
  Race = "American Indian or Alaska Native Alone"
)

# Nebraska
bdh_wnhp_nebraska <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...317`,
  Race = "American Indian or Alaska Native Alone"
)

# Nevada
bdh_wnhp_nevada <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...329`,
  Race = "American Indian or Alaska Native Alone"
)

# New Hampshire
bdh_wnhp_newhampshire <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...341`,
  Race = "American Indian or Alaska Native Alone"
)

# New Jersey
bdh_wnhp_newjersey <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...353`,
  Race = "American Indian or Alaska Native Alone"
)

# New Mexico
bdh_wnhp_newmexico <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...365`,
  Race = "American Indian or Alaska Native Alone"
)

# New York
bdh_wnhp_newyork <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...377`,
  Race = "American Indian or Alaska Native Alone"
)

# North Carolina
bdh_wnhp_northcarolina <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...389`,
  Race = "American Indian or Alaska Native Alone"
)

# North Dakota
bdh_wnhp_northdakota <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...401`,
  Race = "American Indian or Alaska Native Alone"
)

# Ohio
bdh_wnhp_ohio <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...413`,
  Race = "American Indian or Alaska Native Alone"
)

# Oklahoma
bdh_wnhp_oklahoma <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...425`,
  Race = "American Indian or Alaska Native Alone"
)

# Oregon
bdh_wnhp_oregon <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...437`,
  Race = "American Indian or Alaska Native Alone"
)

# Pennsylvania
bdh_wnhp_pennsylvania <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...449`,
  Race = "American Indian or Alaska Native Alone"
)

# Rhode Island
bdh_wnhp_rhodeisland <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...461`,
  Race = "American Indian or Alaska Native Alone"
)

# South Carolina
bdh_wnhp_southcarolina <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...473`,
  Race = "American Indian or Alaska Native Alone"
)

# South Dakota
bdh_wnhp_southdakota <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...485`,
  Race = "American Indian or Alaska Native Alone"
)

# Tennessee
bdh_wnhp_tennessee <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...497`,
  Race = "American Indian or Alaska Native Alone"
)

# Texas
bdh_wnhp_texas <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...509`,
  Race = "American Indian or Alaska Native Alone"
)

# Utah
bdh_wnhp_utah <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...521`,
  Race = "American Indian or Alaska Native Alone"
)

# Vermont
bdh_wnhp_vermont <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...533`,
  Race = "American Indian or Alaska Native Alone"
)

# Virginia
bdh_wnhp_virginia <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...545`,
  Race = "American Indian or Alaska Native Alone"
)

# Washington
bdh_wnhp_washington <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...557`,
  Race = "American Indian or Alaska Native Alone"
)

# West Virginia
bdh_wnhp_westvirginia <- tibble(
  Years =us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...569`,
  Race = "American Indian or Alaska Native Alone"
)

# Wisconsin
bdh_wnhp_wisconsin <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...581`,
  Race = "American Indian or Alaska Native Alone"
)

# Wyoming
bdh_wnhp_wyoming <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...593`,
  Race = "American Indian or Alaska Native Alone"
)

# Puerto Rico
bdh_wnhp_puertorico <- tibble(
  Years = us_AmericanIndianorAlaskaNativeAlone_data$Years,
  Percentage_wnhp_men = us_AmericanIndianorAlaskaNativeAlone_data$`...605`,
  Race = "American Indian or Alaska Native Alone"
)

# Combine all states
combined_data_wnhp <- bind_rows(
  bdh_wnhp_alabama,
  bdh_wnhp_alaska,
  bdh_wnhp_arizona,
  bdh_wnhp_arkansas,
  bdh_wnhp_california,
  bdh_wnhp_colorado,
  bdh_wnhp_connecticut,
  bdh_wnhp_delaware,
  bdh_wnhp_florida,
  bdh_wnhp_georgia,
  bdh_wnhp_hawaii,
  bdh_wnhp_idaho,
  bdh_wnhp_illinois,
  bdh_wnhp_indiana,
  bdh_wnhp_iowa,
  bdh_wnhp_kansas,
  bdh_wnhp_kentucky,
  bdh_wnhp_louisiana,
  bdh_wnhp_maine,
  bdh_wnhp_maryland,
  bdh_wnhp_massachusetts,
  bdh_wnhp_michigan,
  bdh_wnhp_minnesota,
  bdh_wnhp_mississippi,
  bdh_wnhp_missouri,
  bdh_wnhp_montana,
  bdh_wnhp_nebraska,
  bdh_wnhp_nevada,
  bdh_wnhp_newhampshire,
  bdh_wnhp_newjersey,
  bdh_wnhp_newmexico,
  bdh_wnhp_newyork,
  bdh_wnhp_northcarolina,
  bdh_wnhp_northdakota,
  bdh_wnhp_ohio,
  bdh_wnhp_oklahoma,
  bdh_wnhp_oregon,
  bdh_wnhp_pennsylvania,
  bdh_wnhp_rhodeisland,
  bdh_wnhp_southcarolina,
  bdh_wnhp_southdakota,
  bdh_wnhp_tennessee,
  bdh_wnhp_texas,
  bdh_wnhp_utah,
  bdh_wnhp_vermont,
  bdh_wnhp_virginia,
  bdh_wnhp_washington,
  bdh_wnhp_westvirginia,
  bdh_wnhp_wisconsin,
  bdh_wnhp_wyoming,
  bdh_wnhp_puertorico
)

print(combined_data_wnhp)

```

5.  **Male, Asian Alone, Across all U.S. States + Puerto Rico (Status: Cleaned)**

=======
>>>>>>> 6498af32f57b592345d4a47946b48c43f270969e
```{r}
create_dataframe <- function(race_names, state_names, acs_data) {
  race_data <- list()
  for (race in race_names) {
    state_data <- list()
    for (index in 1:51) {
      state = state_names[index]
      multiplier <- which(race_names == race) 
      string2 <- rep("*", multiplier)
      label <- paste("Bachelor's degree or higher", paste(string2, collapse = ""), 
                     sep = "")
      filtered_data <- filter(acs_data, Label == label)
      number <- 9 + 12 * (index - 1)
      state_data[[state]] <- tibble(
        State = state,
        Years = filtered_data$Years,
        Percentage = filtered_data[[paste0("...", number)]],
        Race = race
      )
    }
    combined_state <- bind_rows(state_data)
    race_data[[race]] <- combined_state
  }
  # if you want separate tables for each race, comment out this line of data
  race_data <- bind_rows(race_data)

  return(race_data)
}

male_data <- create_dataframe(race_names, state_names, acs_data)
```


```{r}
write_csv(male_data, here::here('dataset', 'ACS_Male_Final.csv'))
```