### Blog Post 5
04/15/2024


We are planning on combining data from three sources: The World Bank, ACS data supplied by the census bureau, and data from the 2020 and 2010 census as well. Our goal is to paint a complete picture of a variety of variables and demographics of the United States, including location, level of educational attainment, employment information, and potentially even income. Our goal is to have a variety of variables such as these to help us get a better understanding of the disparities faced by U.S. citizens, and women in particular. We have reached the point where our data is mostly clean, but have not actually merged the data frames together yet. One example of a set of data points that we would like to combine is educational attainment data for each gender from the ACS survey that spans from a high school education to a completed Bachelor's degree with data from the World Bank pertaining to Masters and Doctorate degrees. Some initial findings we found, through our cleaned dataset, is that there is a huge division of the percentage of people getting education among different races. For example, the category “white alone” and “asian alone” shows a higher percentage of education rate compared to the category “black alone.” This will allow us to examine the gap in educational attainment between genders on all levels of the system, and may help us to draw interesting conclusions.
