---
title: "Male Data Cleaning"
editor: visual
---

1.  **Male, White-alone, Across all U.S. States + Puerto Rico (Status: Cleaned)**

```{r}
library(readxl)
library(dplyr)
library(tibble)

acs_data <- read_excel("dataset/acsfinale.xlsx")

# Alabama
alabama_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_alabama <- tibble(
  Years = alabama_data$Years,
  Percentage_men = alabama_data$`Alabama...9`,
  Race = "White Alone")

# Alaska
alaska_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_alaska <- tibble(
  Years = alaska_data$Years,
  Percentage_men = alaska_data$`...21`,
  Race = "White Alone"
)


# Arizona
arizona_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_arizona <- tibble(
  Years = arizona_data$Years,
  Percentage_men = arizona_data$`...33`,
  Race = "White Alone"
)

# Arkansas
arkansas_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_arkansas <- tibble(
  Years = arkansas_data$Years,
  Percentage_men = arkansas_data$`...45`,
  Race = "White Alone"
)

# California
california_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_california <- tibble(
  Years = california_data$Years,
  Percentage_men = california_data$`...57`,
  Race = "White Alone"
)

# Colorado
colorado_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_colorado <- tibble(
  Years = colorado_data$Years,
  Percentage_men = colorado_data$`...69`,
  Race = "White Alone"
)

# Connecticut
connecticut_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_connecticut <- tibble(
  Years = connecticut_data$Years,
  Percentage_men = connecticut_data$`...81`,
  Race = "White Alone"
)

# Delaware
delaware_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_delaware <- tibble(
  Years = delaware_data$Years,
  Percentage_men = delaware_data$`...93`,
  Race = "White Alone"
)

# Florida
florida_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_florida <- tibble(
  Years = florida_data$Years,
  Percentage_men = florida_data$`...105`,
  Race = "White Alone"
)

# Georgia
georgia_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_georgia <- tibble(
  Years = georgia_data$Years,
  Percentage_men = georgia_data$`...117`,
  Race = "White Alone"
)

# Hawaii
hawaii_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_hawaii <- tibble(
  Years = hawaii_data$Years,
  Percentage_men = hawaii_data$`...129`,
  Race = "White Alone"
)

# Idaho
idaho_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_idaho <- tibble(
  Years = idaho_data$Years,
  Percentage_men = idaho_data$`...141`,
  Race = "White Alone"
)

# Illinois
illinois_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_illinois <- tibble(
  Years = illinois_data$Years,
  Percentage_men = illinois_data$`...153`,
  Race = "White Alone"
)

# Indiana
indiana_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_indiana <- tibble(
  Years = indiana_data$Years,
  Percentage_men = indiana_data$`...165`,
  Race = "White Alone"
)

# Iowa
iowa_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_iowa <- tibble(
  Years = iowa_data$Years,
  Percentage_men = iowa_data$`...177`,
  Race = "White Alone"
)

# Kansas
kansas_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_kansas <- tibble(
  Years = kansas_data$Years,
  Percentage_men = kansas_data$`...189`,
  Race = "White Alone"
)

# Kentucky
kentucky_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_kentucky <- tibble(
  Years = kentucky_data$Years,
  Percentage_men = kentucky_data$`...201`,
  Race = "White Alone"
)

# Louisiana
louisiana_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_louisiana <- tibble(
  Years = louisiana_data$Years,
  Percentage_men = louisiana_data$`...213`,
  Race = "White Alone"
)

# Maine
maine_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_maine <- tibble(
  Years = maine_data$Years,
  Percentage_men = maine_data$`...225`,
  Race = "White Alone"
)

# Maryland
maryland_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_maryland <- tibble(
  Years = maryland_data$Years,
  Percentage_men = maryland_data$`...237`,
  Race = "White Alone"
)

# Massachusetts
massachusetts_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_massachusetts <- tibble(
  Years = massachusetts_data$Years,
  Percentage_men = massachusetts_data$`...249`,
  Race = "White Alone"
)

# Michigan
michigan_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_michigan <- tibble(
  Years = michigan_data$Years,
  Percentage_men = michigan_data$`...261`,
  Race = "White Alone"
)

# Minnesota
minnesota_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_minnesota <- tibble(
  Years = minnesota_data$Years,
  Percentage_men = minnesota_data$`...273`,
  Race = "White Alone"
)

# Mississippi
mississippi_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_mississippi <- tibble(
  Years = mississippi_data$Years,
  Percentage_men = mississippi_data$`...285`,
  Race = "White Alone"
)

# Missouri
missouri_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_missouri <- tibble(
  Years = missouri_data$Years,
  Percentage_men = missouri_data$`...397`,
  Race = "White Alone"
)

# Montana
montana_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_montana <- tibble(
  Years = montana_data$Years,
  Percentage_men = montana_data$`...309`,
  Race = "White Alone"
)

# Nebraska
nebraska_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_nebraska <- tibble(
  Years = nebraska_data$Years,
  Percentage_men = nebraska_data$`...321`,
  Race = "White Alone"
)

# Nevada
nevada_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_nevada <- tibble(
  Years = nevada_data$Years,
  Percentage_men = nevada_data$`...333`,
  Race = "White Alone"
)

# New Hampshire
newhampshire_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_newhampshire <- tibble(
  Years = newhampshire_data$Years,
  Percentage_men = newhampshire_data$`...345`,
  Race = "White Alone"
)

# New Jersey
newjersey_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_newjersey <- tibble(
  Years = newjersey_data$Years,
  Percentage_men = newjersey_data$`...357`,
  Race = "White Alone"
)

# New Mexico
newmexico_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_newmexico <- tibble(
  Years = newmexico_data$Years,
  Percentage_men = newmexico_data$`...369`,
  Race = "White Alone"
)

# New York
newyork_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_newyork <- tibble(
  Years = newyork_data$Years,
  Percentage_men = newyork_data$`...381`,
  Race = "White Alone"
)

# North Carolina
northcarolina_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_northcarolina <- tibble(
  Years = northcarolina_data$Years,
  Percentage_men = northcarolina_data$`...393`,
  Race = "White Alone"
)

# North Dakota
northdakota_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_northdakota <- tibble(
  Years = northdakota_data$Years,
  Percentage_men = northdakota_data$`...405`,
  Race = "White Alone"
)

# Ohio
ohio_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_ohio <- tibble(
  Years = ohio_data$Years,
  Percentage_men = ohio_data$`...417`,
  Race = "White Alone"
)

# Oklahoma
oklahoma_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_oklahoma <- tibble(
  Years = oklahoma_data$Years,
  Percentage_men = oklahoma_data$`...429`,
  Race = "White Alone"
)

# Oregon
oregon_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_oregon <- tibble(
  Years = oregon_data$Years,
  Percentage_men = oregon_data$`...441`,
  Race = "White Alone"
)

# Pennsylvania
pennsylvania_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_pennsylvania <- tibble(
  Years = pennsylvania_data$Years,
  Percentage_men = pennsylvania_data$`...453`,
  Race = "White Alone"
)

# Rhode Island
rhodeisland_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_rhodeisland <- tibble(
  Years = rhodeisland_data$Years,
  Percentage_men = rhodeisland_data$`...465`,
  Race = "White Alone"
)

# South Carolina
southcarolina_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_southcarolina <- tibble(
  Years = southcarolina_data$Years,
  Percentage_men = southcarolina_data$`...477`,
  Race = "White Alone"
)

# South Dakota
southdakota_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_southdakota <- tibble(
  Years = southdakota_data$Years,
  Percentage_men = southdakota_data$`...489`,
  Race = "White Alone"
)

# Tennessee
tennessee_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_tennessee <- tibble(
  Years = tennessee_data$Years,
  Percentage_men = tennessee_data$`...501`,
  Race = "White Alone"
)

# Texas
texas_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_texas <- tibble(
  Years = texas_data$Years,
  Percentage_men = texas_data$`...513`,
  Race = "White Alone"
)

# Utah
utah_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_utah <- tibble(
  Years = utah_data$Years,
  Percentage_men = utah_data$`...525`,
  Race = "White Alone"
)

# Vermont
vermont_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_vermont <- tibble(
  Years = vermont_data$Years,
  Percentage_men = vermont_data$`...537`,
  Race = "White Alone"
)

# Virginia
virginia_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_virginia <- tibble(
  Years = virginia_data$Years,
  Percentage_men = virginia_data$`...549`,
  Race = "White Alone"
)

# Washington
washington_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_washington <- tibble(
  Years = washington_data$Years,
  Percentage_men = washington_data$`...561`,
  Race = "White Alone"
)

# West Virginia
westvirginia_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_westvirginia <- tibble(
  Years = westvirginia_data$Years,
  Percentage_men = westvirginia_data$`...573`,
  Race = "White Alone"
)

# Wisconsin
wisconsin_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_wisconsin <- tibble(
  Years = wisconsin_data$Years,
  Percentage_men = wisconsin_data$`...585`,
 

 Race = "White Alone"
)

# Wyoming
wyoming_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_wyoming <- tibble(
  Years = wyoming_data$Years,
  Percentage_men = wyoming_data$`...597`,
  Race = "White Alone"
)

# Puerto Rico
puertorico_data <- filter(acs_data, Label == "Bachelor's degree or higher*")
bdh_whitealone_puertorico <- tibble(
  Years = puertorico_data$Years,
  Percentage_men = puertorico_data$`...597`,
  Race = "White Alone"
)

# Combine all tibbles into one
combined_data_malewhitealone <- bind_rows(
  bdh_whitealone_alabama,
  bdh_whitealone_alaska,
  bdh_whitealone_arizona,
  bdh_whitealone_arkansas,
  bdh_whitealone_california,
  bdh_whitealone_colorado,
  bdh_whitealone_connecticut,
  bdh_whitealone_delaware,
  bdh_whitealone_florida,
  bdh_whitealone_georgia,
  bdh_whitealone_hawaii,
  bdh_whitealone_idaho,
  bdh_whitealone_illinois,
  bdh_whitealone_indiana,
  bdh_whitealone_iowa,
  bdh_whitealone_kansas,
  bdh_whitealone_kentucky,
  bdh_whitealone_louisiana,
  bdh_whitealone_maine,
  bdh_whitealone_maryland,
  bdh_whitealone_massachusetts,
  bdh_whitealone_michigan,
  bdh_whitealone_minnesota,
  bdh_whitealone_mississippi,
  bdh_whitealone_missouri,
  bdh_whitealone_montana,
  bdh_whitealone_nebraska,
  bdh_whitealone_nevada,
  bdh_whitealone_newhampshire,
  bdh_whitealone_newjersey,
  bdh_whitealone_newmexico,
  bdh_whitealone_newyork,
  bdh_whitealone_northcarolina,
  bdh_whitealone_northdakota,
  bdh_whitealone_ohio,
  bdh_whitealone_oklahoma,
  bdh_whitealone_oregon,
  bdh_whitealone_pennsylvania,
  bdh_whitealone_rhodeisland,
  bdh_whitealone_southcarolina,
  bdh_whitealone_southdakota,
  bdh_whitealone_tennessee,
  bdh_whitealone_texas,
  bdh_whitealone_utah,
  bdh_whitealone_vermont,
  bdh_whitealone_virginia,
  bdh_whitealone_washington,
  bdh_whitealone_westvirginia,
  bdh_whitealone_wisconsin,
  bdh_whitealone_wyoming,
  bdh_whitealone_puertorico
)

print(combined_data_malewhitealone)
```

2.  **Female, White-alone, not Hispanic or Latino, Across all U.S. States + Puerto Rico (Status: Cleaned)**

```{r}

```
