---
title: "Blog Post 1"
author: ""
date: "2024-02-23"
date-modified: "2024-02-23"
draft: FALSE
---

The purpose of this blog post is to highlight three potential data sets that our group may focus on for our final project.

## Data Set #1: Death rates for suicide by race, age, and Hispanic origin in the United States

This data set was gathered from data.gov, a free database provided by the U.S. Government (https://catalog.data.gov/dataset/death-rates-for-suicide-by-sex-race-hispanic-origin-and-age-united-states-020c1). This data set has 6390 objects and 13 columns, and describes U.S. suicide rates from the years 1950 to 2018. Data before 1980 is a decade apart (1950, 1960, 1970, 1980) but yearly after 1980.

There is a large variety of groups that this data set is separated by, including aggregate data, gender, race, and age. This data was collected by the National Center for Health Statistics, and is highly categorized to the point where grabbing specific information from it has potential to be easy, but proper sorting may prove to be a challenge. Cleaning of the data appears to be unnecessary. While this topic is quite bleak, it could provide valuable insight into the well being of many demographics in the United States.

## Data Set #2: USA Unemployment Rates by Demographics & Race

The data set is from Kaggle: https://www.kaggle.com/datasets/asaniczka/unemployment-rates-by-demographics-1978-2023?resource=download This data set from Kaggle titled "Unemployment Rates by Demographics 1978-2023" contains data related to unemployment rates segmented by various demographic factors in the U.S. over a period spanning from 1978 to 2023. The data set includes 122 columns, including information of unemployment rates for various age groups, education levels, genders, races, and more. The data set includes 537 rows, which the frequency of data collecting is monthly from December 1978 to July 2023.

The data is sourced from the Economic Policy Institute’s State of Working America Data Library and economic research conducted by the Federal Reserve Bank of St. Louis. The purpose is to monitor and analyze employment trends in the population. I think we are able to load/clean this data because the segmentation is clear in columns so it is easy for us to screen out the exact data columns we are looking for for our main research focus and topic. There is no N/A in this data set. The main questions I hope to address with this dataset is to find relationship between education level and unemployment rate and find the trend for different demographic groups across time span. 

## Data Set #3: Educational Attainment of Genders and Race Groups across various age groups (US Census Bureau)

The data set is from the United States Census Bureau as part of the Bureau's 'American Community Survey'. The data set can be accessed by the following link: <https://bit.ly/49WpvK9>. This data set comprises of educational attainment of different age groups, the educational attainment of different race categories, the poverty rate for ages 25 by educational attainment level, and the inflation-adjusted yearly median earnings by race and educational attainment. We selected this data set as it contains a wealth of useful information, and ultimately contains figures for those stated variables for females (also comes complete with percentages also!). In addition, the data also includes specific margin of errors (at 90% margin of error) for each data point it includes - hence boosting its reliability.

The data set ranges from 2010 to 2022. A challenge is that the data set does not put all the data across 2010 - 2022 in one file (i.e., it separates them for observations for each year, resulting in 12 separate files). As of now, we have tried merging them into one file to ease reading. Nonetheless, we acknowledge that the data is not tidy and extensive data tidying is needed to process the data into the format we want. Technically, each separate file consists of 71 rows and 13 columns. There are also some parts of the data which are not available (i.e., denoted by '(X)') - although only a negligible amount.

Ultimately, we conclude that this data set could prove extremely useful if we are able to 'tidy' it well.

(Further information: For more supporting documentation on the accuracy of this data set (e.g., subject definitions, data accuracy, and statistical testing, it can be found on the Technical Documentation of the American Community Survey website in the following link: <https://bit.ly/3SVaf9f>)
