### Blog Post 7
04/29/2024

We are in a pretty good spot for finishing up the project this week. We have finally narrowed our data down to two, highly detailed data sets. We are examining how the disparity that women face, primarily in the workplace, is reflected across different racial groups in the United States. We have our data cleaned and in a state where it can be merged easily. Our primary variables which we are focusing on are income and educational attainment of a bachelors degree. We also plan to use further ACS data to create "heat maps" of the United States to highlight disparities such as the proportion of citizens living above the poverty line by state. All that remains is for us to put this data into digestible figures and tables and decide what regression technique we would like to use. To us, the most appealing regression techniques are a Time-Series regression model and a categorical regression model. We plan to discuss this further and troubleshoot these ideas before our final submission.